#!/usr/bin/env bash
# help.sh — print the project cheatsheet for box.
# `cheatsheet.md` is generated by the in-container Claude on first run
# (see instruction.md). Re-launch ./bin/box and ask Claude to
# refresh the cheatsheet if it gets stale.

set -euo pipefail

cd "$(dirname "$0")"

if [ -f cheatsheet.md ]; then
  cat cheatsheet.md
else
  cat <<'EOF'
No cheatsheet.md found yet.

Launch the container with ./bin/box and ask Claude to set up the
project — it will read the README, install dependencies if needed, and
write cheatsheet.md to the project root.
EOF
fi
